# Generated by Django 5.2.5 on 2025-08-29 07:59

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('kind', models.CharField(choices=[('movie', 'Фильм'), ('book', 'Книга'), ('other', 'Другое')], default='other', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('author', models.CharField(blank=True, max_length=255)),
                ('weight', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='quotes.source')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('value', models.SmallIntegerField(choices=[(1, 'like'), (-1, 'dislike')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='quotes.quote')),
            ],
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('text')), models.F('source'), name='uq_quote_text_source_ci'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('session_key', 'quote')},
        ),
    ]
